### ISSUE TITLE
building example code failed

### ISSUE THREAD

**Issue by spTorin** [crystallabs/tput#1]
$ crystal version
Crystal 0.32.0 [6952aacb3] (2019-12-11)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
---

$ crystal build

```
In lib/tput/src/methods.cr:521:22

 521 | _write("\x1b[" + param + "A")
                      ^
Error: no overload matches 'String#+' with type Int32

Overloads are:
 - String#+(other : self)
 - String#+(char : Char)
```

**Comment by docelic** [comment]
Thanks for the report, the issue should be fixed at this time.

The quick solution was to just add #to_s.

A better solution for later, when the overall functionality gets some more testing in practice, will be to replace literal string concatenation with direct writing to String.builder or to an IO.
